on:
  workflow_call:

jobs:
  CodeQuality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest
        
      - name: Lint code
        run: |
          flake8 . --exclude=*lib/*
      
      - name: Run tests
        run: |
          pytest
